// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD59qPlFtOLTLKgla1bnXFTL_hXpxVtMEc',
    appId: '1:322590749854:android:548afde32832515dbbf78f',
    messagingSenderId: '322590749854',
    projectId: 'chat-app-77f21',
    storageBucket: 'chat-app-77f21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbf_MZBiufFm-FYK2jSRAtI9UDxA3PnDU',
    appId: '1:322590749854:ios:1a54e08cb7a04fcdbbf78f',
    messagingSenderId: '322590749854',
    projectId: 'chat-app-77f21',
    storageBucket: 'chat-app-77f21.appspot.com',
    androidClientId: '322590749854-9fevps79ssku28l4phd1l9t5onphjdsi.apps.googleusercontent.com',
    iosClientId: '322590749854-a1oq9j66su9bp5ofd14lbpt4m7sfnodc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
